### ISSUE TITLE
Update Formulas Builder/Guide

### ISSUE THREAD

**Issue by davewilks** [cloud-elements/devportal#470]
## Description
As a Cloud Elements user, I need access to detailed documentation about Formula Builder so I can successfully build workflows.

In general, the steps will be:
- [ ] Assess the current state of the Formulas Guide
- [ ] Create a simple documentation plan to update the guide
   - [ ] Write Overview #647
   - [ ] Write Build a Formula Template #646
   - [ ] Write Configure a Formula Instance #652
   - [ ] Write Steps Reference Content #648
   - [ ] Write Examples #649
   - [ ] Single threaded vs. multithreaded formulas #392 
   - [ ] Formula tips, best practices and FAQ #393 
   - [x] How to recover lost formulas (This might no be applicable) #394 
   - [ ] Sub formulas - How to create and manage them #395 
   - [ ] Formula context JSON content #396 
   - [ ] Trigger Management #397 
   - [ ] API and UI content like executions and monitoring performance #651 
- [ ] Implement the content in the dev portal
- [ ] Evaluate the changes

**Comment by rjmatt** [comment]
Add a section on Events & Formula Executions.  Basically a large Troubleshooting section.
